"use client";

import { useState } from "react";
import Link from "next/link";
import { updateCompany } from "@/app/company/actions";
import { createClient } from "@/lib/supabase/client";
import { Icon } from "@/components/ui/icons";

const industries = ["Tecnologia e SaaS","Desenvolvimento de software","TI e infraestrutura","Eletrônicos","E-commerce","Varejo","Atacado","Marketing e publicidade","Design e criação","Contabilidade","Advocacia","Consultoria","Imobiliária","Restaurante e alimentação","Delivery","Saúde e clínica","Odontologia","Academia e fitness","Educação e cursos","Construção e engenharia","Arquitetura","Transporte e logística","Indústria","Agronegócio","Serviços profissionais","Outros"];

export function CompanyPersonalization({ initialCompany, canEdit }: { initialCompany: any; canEdit: boolean }) {
  const [form,setForm]=useState({name:initialCompany?.name??"",description:initialCompany?.description??"",industry:initialCompany?.industry??"",businessSegment:initialCompany?.business_segment??"",document:initialCompany?.document??"",phone:initialCompany?.phone??"",email:initialCompany?.email??"",address:initialCompany?.address??"",city:initialCompany?.city??"",state:initialCompany?.state??"",themePrimary:initialCompany?.theme_primary??"#2563eb",themeSecondary:initialCompany?.theme_secondary??"#0f172a",logoUrl:initialCompany?.logo_url??""});
  const [preview,setPreview]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [status,setStatus]=useState("");
  async function upload(file:File){if(!canEdit)return;if(file.size>5*1024*1024)return setStatus("A imagem precisa ter até 5 MB.");const supabase=createClient();const path=initialCompany.id+"/logo-"+Date.now();const {error}=await supabase.storage.from("company-assets").upload(path,file,{contentType:file.type,upsert:false});if(error)return setStatus(error.message);setForm(f=>({...f,logoUrl:path}));setPreview(URL.createObjectURL(file));}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setStatus("");try{await updateCompany(form);setStatus("Alterações salvas.");}catch(error){setStatus(error instanceof Error?error.message:"Não foi possível salvar.");}finally{setSaving(false);}}
  const set=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
  return <><div className="mb-8"><Link href="/company" className="text-xs font-bold text-blue-600">← Voltar para empresa</Link><p className="mt-5 text-[11px] font-bold uppercase tracking-[.22em] text-blue-600">Identidade da empresa</p><h1 className="mt-2 text-3xl font-black tracking-tight">Personalização</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Logo, descrição, nicho, dados e identidade visual em um só lugar.</p></div>
  <form onSubmit={save} className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
    <section className="vicos-card rounded-[24px] p-6"><h2 className="text-lg font-black">Identidade visual</h2><div className="mt-5 flex items-center gap-4">{preview?<img src={preview} alt="" className="h-24 w-24 rounded-[24px] object-cover ring-1 ring-slate-200"/>:<div className="vicos-orb h-24 w-24 rounded-[24px] text-2xl font-black text-blue-600">{form.name.slice(0,1).toUpperCase()||"V"}</div>}<label className={canEdit?"vicos-button-secondary cursor-pointer":"vicos-button-secondary opacity-50"}>Alterar foto<input disabled={!canEdit} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><p className="mt-3 text-[11px] leading-5 text-slate-400">PNG, JPG ou WebP · até 5 MB.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Cor principal<input disabled={!canEdit} type="color" value={form.themePrimary} onChange={e=>set("themePrimary",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white p-1"/></label><label className="text-xs font-bold text-slate-600">Cor secundária<input disabled={!canEdit} type="color" value={form.themeSecondary} onChange={e=>set("themeSecondary",e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white p-1"/></label></div></section>
    <section className="vicos-card rounded-[24px] p-6"><h2 className="text-lg font-black">Dados da empresa</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">
      {([["Nome da empresa","name"],["Documento","document"],["Telefone","phone"],["E-mail","email"],["Cidade","city"],["Estado","state"],["Segmento","businessSegment"]] as const).map(([label,key])=><label key={key} className="text-xs font-bold text-slate-600">{label}<input disabled={!canEdit} value={form[key]} onChange={e=>set(key,e.target.value)} className="vicos-input mt-2"/></label>)}
      <label className="text-xs font-bold text-slate-600 sm:col-span-2">Nicho<select disabled={!canEdit} value={form.industry} onChange={e=>set("industry",e.target.value)} className="vicos-input mt-2"><option value="">Selecione o nicho</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="text-xs font-bold text-slate-600 sm:col-span-2">Descrição<textarea disabled={!canEdit} value={form.description} onChange={e=>set("description",e.target.value)} rows={4} className="vicos-input mt-2 resize-none" placeholder="Conte em poucas linhas o que sua empresa faz."/></label>
      <label className="text-xs font-bold text-slate-600 sm:col-span-2">Endereço<textarea disabled={!canEdit} value={form.address} onChange={e=>set("address",e.target.value)} rows={2} className="vicos-input mt-2 resize-none"/></label>
    </div>{!canEdit&&<p className="mt-5 text-xs text-amber-700">Somente administradores podem alterar a identidade da empresa.</p>}{canEdit&&<button disabled={saving} className="vicos-button mt-6 disabled:opacity-60">{saving?"Salvando…":"Salvar alterações"} <Icon name="check" size={15}/></button>}{status&&<p className="mt-3 text-xs font-semibold text-slate-500">{status}</p>}</section>
  </form></>;
}