import { DashboardNav } from "@/components/layout/dashboard-nav";
import { PageHeader } from "@/components/layout/page-header";
import { getCurrentUserContext } from "@/lib/db/context";
import { updateTeamMemberRole } from "@/app/team/actions";

const roleLabels:Record<string,string>={admin:"Administrador",manager:"Gerente",operator:"Operador",viewer:"Visualizador"};

export default async function TeamPage({searchParams}:{searchParams?:Promise<{invited?:string}>}) {
  const {supabase,membership}=await getCurrentUserContext();
  const {data:members,error}=await supabase.from("users").select("id,name,email,role,created_at,updated_at").eq("company_id",membership.company_id).order("name");
  if(error) throw new Error(error.message);
  async function changeRole(formData:FormData){"use server";await updateTeamMemberRole(String(formData.get("userId")??""),String(formData.get("role")??"") as "admin"|"manager"|"operator"|"viewer");}
  const query=searchParams?await searchParams:{};
  const canManage=membership.role==="admin";
  return <div className="flex min-h-screen bg-slate-50"><DashboardNav active="Equipe"/><main className="vicos-mobile-main flex-1 px-5 py-7 md:px-8 lg:px-10 lg:py-9"><PageHeader eyebrow="Organização" title="Equipe" description="Gerencie usuários, funções e níveis de acesso da sua empresa." action={canManage?"Convidar membro":undefined} href={canManage?"/team/invite":undefined}/>{query.invited==="1"&&<div className="mb-5 rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Convite enviado. O colaborador receberá um e-mail para concluir o acesso.</div>}<section className="vicos-card overflow-hidden rounded-[24px]"><div className="grid grid-cols-[1fr_170px] border-b border-slate-200/70 bg-slate-50/70 px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-slate-400 md:grid-cols-[1.4fr_1fr_220px]"><span>Membro</span><span className="hidden md:block">E-mail</span><span>Nível</span></div><div className="divide-y divide-slate-100">{(members??[]).map(member=><div key={member.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1.4fr_1fr_220px] md:items-center"><div className="min-w-0"><p className="truncate text-sm font-black text-slate-900">{member.name||"Sem nome"}</p><p className="truncate text-xs text-slate-400 md:hidden">{member.email}</p></div><p className="hidden truncate text-xs text-slate-500 md:block">{member.email}</p>{canManage&&member.id!==membership.id?<form action={changeRole} className="flex items-center gap-2"><input type="hidden" name="userId" value={member.id}/><select name="role" defaultValue={member.role??"operator"} className="vicos-input flex-1"><option value="admin">Administrador</option><option value="manager">Gerente</option><option value="operator">Operador</option><option value="viewer">Visualizador</option></select><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-500 hover:text-slate-900" type="submit">Salvar</button></form>:<span className="vicos-chip w-fit">{roleLabels[member.role??""]??member.role??"—"}</span>}</div>)}{!members?.length&&<div className="p-10 text-center text-sm text-slate-400">Nenhum membro encontrado.</div>}</div></section></main></div>;
}
