"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { clearLocalFirstData } from "@/lib/local-first/db";
import { updateProfile } from "@/app/profile/actions";

export function ProfileClient({initialProfile,role}:{initialProfile:any;role:string}) {
 const router=useRouter();
 const [f,setF]=useState({name:initialProfile?.name??"",jobTitle:initialProfile?.job_title??"",bio:initialProfile?.bio??"",avatarUrl:initialProfile?.avatar_url??"",presence:initialProfile?.presence??"online"});
 const [preview,setPreview]=useState<string|null>(null); const [status,setStatus]=useState(""); const [saving,setSaving]=useState(false); const [loggingOut,setLoggingOut]=useState(false);
 async function upload(file:File){if(file.size>5*1024*1024)return setStatus("A imagem precisa ter até 5 MB.");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const path=initialProfile.company_id+"/profiles/"+user.id+"/avatar-"+Date.now();const {error}=await supabase.storage.from("company-assets").upload(path,file,{contentType:file.type,upsert:false});if(error)return setStatus(error.message);setF({...f,avatarUrl:path});setPreview(URL.createObjectURL(file));}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{await updateProfile(f);setStatus("Perfil atualizado.");}catch(e){setStatus(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setSaving(false);}}
 async function logout(){setLoggingOut(true);const supabase=createClient();const {error}=await supabase.auth.signOut();if(error){setStatus(error.message);setLoggingOut(false);return;}await clearLocalFirstData();router.replace("/login");router.refresh();}
 return <><div className="mb-8"><Link href="/dashboard" className="text-xs font-bold text-blue-600">← Voltar ao dashboard</Link><p className="mt-5 text-[11px] font-bold uppercase tracking-[.22em] text-blue-600">Conta</p><h1 className="mt-2 text-3xl font-black">Meu perfil</h1><p className="mt-2 text-sm text-slate-500">Como os outros membros da empresa veem você no VicOs.</p></div><form onSubmit={save} className="max-w-3xl vicos-card rounded-[24px] p-6"><div className="flex items-center gap-4">{preview?<img src={preview} alt="" className="h-20 w-20 rounded-full object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-full bg-slate-900 text-lg font-bold text-white">{f.name.slice(0,2).toUpperCase()||"EU"}</div>}<label className="vicos-button-secondary cursor-pointer">Alterar foto<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Nome<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} className="vicos-input mt-2"/></label><label className="text-xs font-bold text-slate-600">Cargo<input value={f.jobTitle} onChange={e=>setF({...f,jobTitle:e.target.value})} className="vicos-input mt-2"/></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Bio<textarea rows={4} value={f.bio} onChange={e=>setF({...f,bio:e.target.value})} className="vicos-input mt-2 resize-none"/></label><label className="text-xs font-bold text-slate-600">Status<select value={f.presence} onChange={e=>setF({...f,presence:e.target.value})} className="vicos-input mt-2"><option value="online">Disponível</option><option value="away">Ausente</option><option value="busy">Não perturbe</option><option value="offline">Offline</option></select></label><div className="flex items-end"><span className="text-xs text-slate-400">Cargo no VicOs: {role}</span></div></div><div className="mt-6 flex flex-wrap items-center gap-3"><button disabled={saving} className="vicos-button disabled:opacity-60">{saving?"Salvando…":"Salvar perfil"}</button><button type="button" disabled={loggingOut} onClick={()=>void logout()} className="rounded-xl border border-rose-200 bg-white px-4 py-2.5 text-sm font-bold text-rose-600 hover:bg-rose-50">{loggingOut?"Saindo…":"Sair da conta"}</button></div>{status&&<p className="mt-3 text-xs text-slate-500">{status}</p>}</form></>;
}
