"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/ui/icons";
import { useLocalFirst } from "@/lib/local-first/use-local-first";

type Income={id:string;company_id:string;description:string;amount:number;category:string|null;date:string;payment_method:string|null;status:string;notes:string|null;created_at:string;updated_at:string};
type Expense={id:string;company_id:string;description:string;amount:number;category:string|null;due_date:string|null;payment_date:string|null;payment_method:string|null;status:string;notes:string|null;created_at:string;updated_at:string};
type Props={companyId:string;initialIncomes:Income[];initialExpenses:Expense[]};

export function FinanceClient({companyId,initialIncomes,initialExpenses}:Props){
 const {data:incomes,upsert:upsertIncome,remove:removeIncome}=useLocalFirst<Income>("incomes","finance:incomes",initialIncomes);
 const {data:expenses,upsert:upsertExpense,remove:removeExpense}=useLocalFirst<Expense>("expenses","finance:expenses",initialExpenses);
 const [description,setDescription]=useState(""); const [amount,setAmount]=useState(""); const [kind,setKind]=useState<"income"|"expense">("income"); const [busy,setBusy]=useState(false);
 const totalIn=useMemo(()=>incomes.reduce((s,x)=>s+Number(x.amount||0),0),[incomes]); const totalOut=useMemo(()=>expenses.reduce((s,x)=>s+Number(x.amount||0),0),[expenses]);
 const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
 async function add(){const value=Number(amount.replace(",","."));if(!description.trim()||!Number.isFinite(value)||value<=0||busy)return;setBusy(true);const now=new Date().toISOString();try{if(kind==="income")await upsertIncome({id:crypto.randomUUID(),company_id:companyId,description:description.trim(),amount:value,category:null,date:now.slice(0,10),payment_method:null,status:"paid",notes:null,created_at:now,updated_at:now});else await upsertExpense({id:crypto.randomUUID(),company_id:companyId,description:description.trim(),amount:value,category:null,due_date:now.slice(0,10),payment_date:null,payment_method:null,status:"pending",notes:null,created_at:now,updated_at:now});setDescription("");setAmount("")}finally{setBusy(false)}}
 const recent=[...incomes.map(x=>({id:x.id,type:"in" as const,description:x.description,amount:Number(x.amount),date:x.date})),...expenses.map(x=>({id:x.id,type:"out" as const,description:x.description,amount:Number(x.amount),date:x.due_date||x.created_at.slice(0,10)}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30);
 return <section className="space-y-5"><div className="grid gap-3 md:grid-cols-3"><div className="vicos-card rounded-[22px] p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Receitas</p><p className="mt-2 text-2xl font-black">{money(totalIn)}</p></div><div className="vicos-card rounded-[22px] p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Despesas</p><p className="mt-2 text-2xl font-black">{money(totalOut)}</p></div><div className="rounded-[22px] border border-blue-100 bg-blue-50/75 p-5"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Resultado</p><p className="mt-2 text-2xl font-black">{money(totalIn-totalOut)}</p></div></div><div className="vicos-card rounded-[22px] p-5"><div className="grid gap-3 md:grid-cols-[150px_1fr_180px_auto]"><select className="vicos-input" value={kind} onChange={e=>setKind(e.target.value as "income"|"expense")}><option value="income">Receita</option><option value="expense">Despesa</option></select><input className="vicos-input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição"/><input className="vicos-input" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0,00"/><button className="vicos-button" disabled={busy} onClick={()=>void add()}>{busy?"Salvando…":"Adicionar"}</button></div><Link href="/finance/new" className="mt-3 inline-block text-xs font-bold text-blue-600">Abrir cadastro completo →</Link></div><div className="vicos-card overflow-hidden rounded-[22px]"><div className="border-b border-slate-200/70 px-5 py-4"><h2 className="font-black">Movimentações recentes</h2></div>{recent.map(x=><div key={x.id} className="flex items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50"><Icon name={x.type==="in"?"arrow-up":"arrow-down"} size={15}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{x.description}</p><p className="text-xs text-slate-400">{new Date(x.date+"T12:00:00").toLocaleDateString("pt-BR")}</p></div><span className="text-sm font-black">{x.type==="in"?"+":"-"} {money(x.amount)}</span><button className="rounded-xl p-2 text-slate-400 hover:text-rose-600" onClick={()=>x.type==="in"?void removeIncome(x.id):void removeExpense(x.id)} aria-label="Excluir"><Icon name="trash" size={15}/></button></div>)}{!recent.length&&<div className="p-10 text-center text-sm text-slate-400">Nenhuma movimentação.</div>}</div></section>;
}