import Link from "next/link";
import { redirect } from "next/navigation";
import { inviteTeamMember } from "@/app/team/actions";
import { getCurrentUserContext } from "@/lib/db/context";

export default async function InviteTeamPage() {
  const {membership}=await getCurrentUserContext();
  if(membership.role!=="admin") return <main className="min-h-screen bg-slate-50 px-6 py-10"><div className="mx-auto max-w-2xl rounded-2xl border border-slate-200 bg-white p-8"><Link href="/team" className="text-sm font-bold text-blue-500">← Voltar para equipe</Link><h1 className="mt-5 text-3xl font-black">Acesso restrito</h1><p className="mt-2 text-sm text-slate-500">Somente administradores podem convidar novos membros.</p></div></main>;
  async function submit(formData:FormData){"use server";await inviteTeamMember({name:String(formData.get("name")??""),email:String(formData.get("email")??""),role:String(formData.get("role")??"operator") as "admin"|"manager"|"operator"|"viewer"});redirect("/team?invited=1");}
  return <main className="min-h-screen bg-slate-50 px-6 py-10"><div className="mx-auto max-w-2xl rounded-2xl border border-slate-200 bg-white p-8"><Link href="/team" className="text-sm font-bold text-blue-500">← Voltar para equipe</Link><h1 className="mt-5 text-3xl font-black">Convidar membro</h1><p className="mt-2 text-sm text-slate-500">Envie um convite e escolha o nível de acesso que esta pessoa terá no VicOs.</p><form action={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-sm font-semibold">Nome</span><input name="name" className="w-full rounded-xl border border-slate-200 px-4 py-3" placeholder="Nome do colaborador" autoComplete="name" required /></label><label className="block"><span className="mb-2 block text-sm font-semibold">E-mail</span><input name="email" type="email" autoComplete="email" className="w-full rounded-xl border border-slate-200 px-4 py-3" placeholder="colaborador@empresa.com" required /></label><label className="block"><span className="mb-2 block text-sm font-semibold">Permissão</span><select name="role" defaultValue="operator" className="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="operator">Operador</option><option value="viewer">Visualizador</option><option value="manager">Gerente</option><option value="admin">Administrador</option></select></label><div className="flex justify-end gap-3"><Link href="/team" className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">Cancelar</Link><button type="submit" className="rounded-xl bg-blue-500 px-5 py-3 text-sm font-bold text-white hover:bg-blue-600">Enviar convite</button></div></form></div></main>;
}
