"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/ui/icons";
import { useLocalFirst } from "@/lib/local-first/use-local-first";

type Contact={id:string;company_id:string;name:string;phone:string;normalized_phone:string;status:string;notes:string|null;country_code:string|null;area_code:string|null;created_at:string;updated_at:string};
type Props={companyId:string;initialData:Contact[]};
export function ContactsClient({companyId,initialData}:Props){
 const {data,upsert,remove}=useLocalFirst<Contact>("contacts",`contacts:list:${companyId}`,initialData); const [search,setSearch]=useState(""); const [status,setStatus]=useState("all"); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [busy,setBusy]=useState(false);
 const visible=useMemo(()=>data.filter(x=>{const q=search.trim().toLowerCase();return(!q||x.name.toLowerCase().includes(q)||x.phone.toLowerCase().includes(q))&&(status==="all"||x.status===status)}),[data,search,status]);
 async function add(){if(!name.trim()||!phone.trim()||busy)return;setBusy(true);const now=new Date().toISOString(),normalized=phone.replace(/\\D/g,"");try{await upsert({id:crypto.randomUUID(),company_id:companyId,name:name.trim(),phone:phone.trim(),normalized_phone:normalized,status:"active",notes:null,country_code:"+55",area_code:normalized.length>=10?normalized.slice(-11).slice(0,2):null,created_at:now,updated_at:now});setName("");setPhone("")}finally{setBusy(false)}}
 return <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[["Total",data.length],["Ativos",data.filter(x=>x.status==="active").length],["Bloqueados",data.filter(x=>x.status==="blocked").length]].map(([a,b])=><div key={a} className="vicos-card rounded-[22px] p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>)}</div><div className="vicos-card rounded-[22px] p-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input className="vicos-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome ou número…"/><select className="vicos-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="blocked">Bloqueados</option><option value="pending">Pendentes</option></select><Link href="/contacts/new" className="vicos-button">Abrir cadastro</Link></div></div><div className="vicos-card rounded-[22px] p-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input className="vicos-input" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do contato"/><input className="vicos-input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+55 11 99999-9999"/><button className="vicos-button" disabled={busy} onClick={()=>void add()}>{busy?"Salvando…":"Adicionar rápido"}</button></div></div><div className="grid gap-2">{visible.map(x=><article key={x.id} className="vicos-card flex items-center gap-4 rounded-[20px] p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon name="users" size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{x.name}</p><p className="mt-1 text-xs text-slate-400">{x.phone}</p></div><span className="vicos-chip hidden sm:inline-flex">{x.status}</span><button className="rounded-xl p-2 text-slate-400 hover:text-rose-600" onClick={()=>void remove(x.id)} aria-label="Excluir"><Icon name="more" size={16}/></button></article>)}{!visible.length&&<div className="vicos-card rounded-[22px] p-10 text-center text-sm text-slate-400">Nenhum contato encontrado.</div>}</div></section>;
}
