"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/ui/icons";
import { useLocalFirst } from "@/lib/local-first/use-local-first";

type Account={id:string;company_id:string;platform:string;external_id:string;display_name:string|null;username:string|null;status:string;notes:string|null;created_at:string;updated_at:string};
type Props={companyId:string;initialData:Account[]};

export function AccountsClient({companyId,initialData}:Props){
 const {data,upsert,remove}=useLocalFirst<Account>("accounts","accounts:list",initialData);
 const [search,setSearch]=useState(""); const [platform,setPlatform]=useState(""); const [externalId,setExternalId]=useState(""); const [busy,setBusy]=useState(false);
 const visible=useMemo(()=>data.filter(x=>{const q=search.trim().toLowerCase();return !q||x.platform.toLowerCase().includes(q)||x.external_id.toLowerCase().includes(q)||(x.display_name||"").toLowerCase().includes(q)||(x.username||"").toLowerCase().includes(q)}),[data,search]);
 async function add(){if(!platform.trim()||!externalId.trim()||busy)return;setBusy(true);const now=new Date().toISOString();try{await upsert({id:crypto.randomUUID(),company_id:companyId,platform:platform.trim(),external_id:externalId.trim(),display_name:null,username:null,status:"active",notes:null,created_at:now,updated_at:now});setPlatform("");setExternalId("")}finally{setBusy(false)}}
 return <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[["Total",data.length],["Ativas",data.filter(x=>x.status==="active").length],["Plataformas",new Set(data.map(x=>x.platform.toLowerCase())).size]].map(([a,b])=><div key={a} className="vicos-card rounded-[22px] p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>)}</div><div className="vicos-card rounded-[22px] p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><input className="vicos-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar plataforma, ID ou nome…"/><Link href="/accounts/new" className="vicos-button">Abrir cadastro</Link></div></div><div className="vicos-card rounded-[22px] p-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input className="vicos-input" value={platform} onChange={e=>setPlatform(e.target.value)} placeholder="Plataforma"/><input className="vicos-input" value={externalId} onChange={e=>setExternalId(e.target.value)} placeholder="ID externo"/><button className="vicos-button" disabled={busy} onClick={()=>void add()}>{busy?"Salvando…":"Adicionar rápido"}</button></div></div><div className="grid gap-2">{data.length?visible.map(x=><article key={x.id} className="vicos-card flex items-center gap-4 rounded-[20px] p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><Icon name="external" size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{x.platform}{x.display_name?" · "+x.display_name:""}</p><p className="mt-1 truncate text-xs text-slate-400">{x.external_id}</p></div><span className="vicos-chip hidden sm:inline-flex">{x.status}</span><button className="rounded-xl p-2 text-slate-400 hover:text-rose-600" onClick={()=>void remove(x.id)} aria-label="Excluir"><Icon name="more" size={16}/></button></article>):<div className="vicos-card rounded-[22px] p-10 text-center text-sm text-slate-400">Nenhuma conta encontrada.</div>}</div></section>;
}