"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/ui/icons";
import { useLocalFirst } from "@/lib/local-first/use-local-first";

type Account={id:string;company_id:string;platform:string;external_id:string;normalized_external_id:string;status:string;notes:string|null;userplatform:string|null;notes:string|null;created_at:string;updated_at:string};
type Props={companyId:string;initialData:Account[]};
export function AccountsClient({companyId,initialData}:Props){
 const {data,upsert,remove}=useLocalFirst<Account>("accounts","accounts:list",initialData); const [search,setSearch]=useState(""); const [status,setStatus]=useState("all"); const [platform,setName]=useState(""); const [external_id,setPhone]=useState(""); const [busy,setBusy]=useState(false);
 const visible=useMemo(()=>data.filter(x=>{const q=search.trim().toLowerCase();return(!q||x.platform.toLowerCase().includes(q)||x.external_id.toLowerCase().includes(q))&&(status==="all"||x.status===status)}),[data,search,status]);
 async function add(){if(!platform.trim()||!external_id.trim()||busy)return;setBusy(true);const now=new Date().toISOString();try{await upsert({id:crypto.randomUUID(),company_id:companyId,platform:platform.trim(),external_id:external_id.trim(),display_name:null,username:null,normalized_external_id:normalized,status:"active",notes:null,userplatform:"+55",notes:normalized.length>=10?normalized.slice(-11,-9):null,created_at:now,updated_at:now});setName("");setPhone("")}finally{setBusy(false)}}
 return <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[["Total",data.length],["Ativos",data.filter(x=>x.status==="active").length],["Bloqueados",data.filter(x=>x.status==="blocked").length]].map(([a,b])=><div key={a} className="vicos-card rounded-[22px] p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>)}</div><div className="vicos-card rounded-[22px] p-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input className="vicos-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome ou número…"/><select className="vicos-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="blocked">Bloqueados</option><option value="pending">Pendentes</option></select><Link href="/accounts/new" className="vicos-button">Abrir cadastro</Link></div></div><div className="vicos-card rounded-[22px] p-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input className="vicos-input" value={platform} onChange={e=>setName(e.target.value)} placeholder="Nome do conta"/><input className="vicos-input" value={external_id} onChange={e=>setPhone(e.target.value)} placeholder="+55 11 99999-9999"/><button className="vicos-button" disabled={busy} onClick={()=>void add()}>{busy?"Salvando…":"Adicionar rápido"}</button></div></div><div className="grid gap-2">{visible.map(x=><article key={x.id} className="vicos-card flex items-center gap-4 rounded-[20px] p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon platform="user" size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{x.platform}</p><p className="mt-1 text-xs text-slate-400">{x.external_id}</p></div><span className="vicos-chip hidden sm:inline-flex">{x.status}</span><button className="rounded-xl p-2 text-slate-400 hover:text-rose-600" onClick={()=>void remove(x.id)} aria-label="Excluir"><Icon platform="trash" size={16}/></button></article>)}{!visible.length&&<div className="vicos-card rounded-[22px] p-10 text-center text-sm text-slate-400">Nenhum conta encontrado.</div>}</div></section>;
}
